import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.TEST_URL||'http://127.0.0.1:5173';
const artifact=process.env.QA_DIR||'work/qa';await mkdir(artifact,{recursive:true});
const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));
try{
  await page.goto(base);await page.waitForSelector('.north-chart');
  assert.match(await page.locator('.north-chart').getAttribute('aria-label'),/Virgo/);
  assert.equal(await page.locator('.north-chart g').count(),12);
  await page.getByRole('button',{name:'South Indian',exact:true}).click();assert.match(await page.locator('.chart-center').innerText(),/Virgo/);
  await page.getByRole('button',{name:'North Indian',exact:true}).click();
  assert.equal(await page.locator('tbody tr').filter({has:page.getByRole('rowheader',{name:'Jupiter R',exact:true})}).locator('.house-numbers').innerText(),'1, 2, 4, 7, 9, 10, 11, 12');
  checks.push('North/South Indian toggle, 12 North Indian houses, numbered planet significations');
  await page.screenshot({path:`${artifact}/desktop.png`,fullPage:true});
  await page.getByRole('button',{name:'Cusps & sub-lords',exact:true}).click();
  assert.equal(await page.locator('tbody tr').count(),12);assert.match(await page.locator('tr.highlight').innerText(),/81\.30711202/);checks.push('All 12 cusps and verified MC displayed');
  await page.getByRole('button',{name:'Dasha periods',exact:true}).click();
  assert.equal(await page.locator('.period').count(),36);
  await page.locator('[data-level="0"][data-index="0"]').click();
  assert.equal(await page.locator('.dasha-column').nth(1).locator('.period').first().locator('.period-name').innerText(),'Mercury');
  await page.locator('[data-level="1"][data-index="2"]').click();
  assert.equal(await page.locator('.dasha-column').nth(2).locator('.period').first().locator('.period-name').innerText(),'Venus');
  await page.locator('#jump-date').fill('1975-10-19');await page.getByRole('button',{name:'Go',exact:true}).click();
  assert.match(await page.locator('.dasha-column').first().locator('.selected').innerText(),/Mercury/);
  await page.getByRole('button',{name:'Next 120-year cycle'}).click();await page.getByRole('button',{name:'Previous 120-year cycle'}).click();
  await page.getByRole('button',{name:'Now',exact:true}).click();
  await page.locator('#date-zone').selectOption('UTC');assert.match(await page.locator('.period').first().innerText(),/\+00:00/);
  checks.push('All four dasha levels, selection, date jump, cycles, Now and UTC display');
  await page.screenshot({path:`${artifact}/dasha.png`,fullPage:true});
  await page.getByRole('button',{name:'Significations',exact:true}).click();assert.equal(await page.locator('.sig-card').count(),9);assert.match(await page.locator('.sig-card').filter({has:page.getByRole('heading',{name:'Ketu',exact:true})}).innerText(),/Aspect · Saturn \(10th\)/);assert.match(await page.locator('.sig-card').filter({has:page.getByRole('heading',{name:'Rahu',exact:true})}).innerText(),/Rahu same sign · Sun/);const marsCard=page.locator('.sig-card').filter({has:page.getByRole('heading',{name:'Mars',exact:true})});assert.match(await marsCard.innerText(),/Star · Rahu\s+1, 2, 9, 11, 12/);assert.match(await marsCard.innerText(),/Sub · Rahu\s+1, 2, 9, 11, 12/);assert.match(await marsCard.locator('.number-chips').innerText(),/1\s+2\s+3\s+8\s+9\s+11\s+12/);checks.push('Four-fold and propagated Rahu/Ketu significations');
  await page.locator('summary').click();await page.locator('[name=node]').selectOption('true');await page.locator('#calculate').click();assert.equal(await page.locator('.pill').innerText(),'True node');
  await page.locator('[name=date]').fill('2024-03-10');await page.locator('[name=hour]').selectOption('2');await page.locator('[name=minute]').fill('30');await page.locator('[name=zone]').fill('America/New_York');await page.locator('#calculate').click();assert.match(await page.locator('#error').innerText(),/did not exist/);checks.push('Node setting and DST gap error');
  await page.locator('[name=date]').fill('2024-11-03');await page.locator('[name=hour]').selectOption('1');await page.locator('#calculate').click();assert.match(await page.locator('#error').innerText(),/occurred twice/);
  await page.locator('[name=fold]').selectOption('later');await page.locator('#calculate').click();assert.ok(await page.locator('#error').isHidden());checks.push('DST fold requires and accepts explicit occurrence');
  await page.locator('#sample').click();
  // Deterministic network fixtures cover search UI, including keyboard selection.
  await page.route('**/geocoding-api.open-meteo.com/**',route=>route.fulfill({json:{results:[{name:'London',admin1:'England',country:'United Kingdom',latitude:51.50853,longitude:-0.12574,timezone:'Europe/London'}]}}));
  await page.locator('#place').fill('London');await page.waitForSelector('[data-place="0"]');await page.locator('#place').press('ArrowDown');await page.locator('#place').press('Enter');
  assert.equal(await page.locator('[name=zone]').inputValue(),'Europe/London');assert.equal(await page.locator('[name=lat]').inputValue(),'51.50853');checks.push('Place keyboard autocomplete resolves coordinates and timezone');
  await page.locator('#place').fill('New place');assert.equal(await page.locator('[name=lat]').inputValue(),'');checks.push('New search clears stale coordinates');
  await page.unroute('**/geocoding-api.open-meteo.com/**');await page.locator('#sample').click();
  await page.getByRole('button',{name:'Birth chart',exact:true}).click();
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:`${artifact}/mobile.png`,fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.getByRole('button',{name:'Dasha periods',exact:true}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`${artifact}/mobile-dasha.png`,fullPage:true});checks.push('390px mobile birth and dasha views have no page overflow');
  await page.setViewportSize({width:1440,height:1100});await page.evaluate(()=>document.documentElement.style.fontSize='32px');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.push('200% root text enlargement does not overflow page');
  assert.deepEqual(errors,[]);checks.push('No uncaught browser errors');
  console.log(JSON.stringify({checks},null,2));await writeFile(`${artifact}/ui-checks.json`,JSON.stringify({checks},null,2));
}finally{await browser.close();}
